version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_tech_assessment
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tech_assessment_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
      - ./DB.json:/docker-entrypoint-initdb.d/DB.json
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh